before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/shusugmt/kubectl-sealer/cmd.Version={{.Version}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.Revision={{.FullCommit}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.Branch={{.Branch}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.BuildUser=goreleaser
      - -X github.com/shusugmt/kubectl-sealer/cmd.BuildDate={{.CommitDate}}
      - -extldflags=-static
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
