before:
  hooks:
    - go mod download
builds:
  - id: kubectl-sealer
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/shusugmt/kubectl-sealer/cmd.Version={{.Version}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.Revision={{.FullCommit}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.Branch={{.Branch}}
      - -X github.com/shusugmt/kubectl-sealer/cmd.BuildUser=goreleaser
      - -X github.com/shusugmt/kubectl-sealer/cmd.BuildDate={{.CommitDate}}
      - -extldflags=-static
archives:
  - id: kubectl-sealer
    builds:
      - kubectl-sealer
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
