# base: https://github.com/kubernetes-sigs/krew-index/blob/84965f2707bbac80d153539a976b25a800daf994/.github/workflows/ci.yml
name: krew-index CI

on: push

jobs:
  build:
    name: Build and Tags
    runs-on: ubuntu-latest
    env:
      KREW_VERSION: v0.4.0
      GO111MODULE: on
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # disable shallow clones

    - name: Install kubectl
      run: |
        set -euo pipefail
        sudo curl -fsSL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubectl
        sudo chmod +x /usr/bin/kubectl

    - name: Install krew
      run: |
        set -euo pipefail
        cd "$(mktemp -d)"
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/${KREW_VERSION}/krew.{tar.gz,yaml}"
        tar zxvf krew.tar.gz
        ./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz

    - name: Install validate-krew-manifest plugin
      run : |
        set -euo pipefail
        export GOBIN=$HOME/bin
        # TODO(corneliusweig): pin validator version after next release
        # go get sigs.k8s.io/krew/cmd/validate-krew-manifest@${KREW_VERSION}
        go get sigs.k8s.io/krew/cmd/validate-krew-manifest@ec169f8c9c53e0aaaf57f1f73fb38590842ceb77

    - name: Validate updated plugin manifests
      run : |
        set -x
        set -euo pipefail
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        find plugins/ -type f |
          tee /dev/stderr |
          xargs -I _ $HOME/bin/validate-krew-manifest -manifest _
